# Generated by Django 3.2.5 on 2021-07-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creat_order', '0002_alter_user_info_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_information',
            name='order_switch',
            field=models.BooleanField(default=True, verbose_name='订单开关状态'),
        ),
    ]
