# Generated by Django 3.2.5 on 2021-07-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creat_order', '0003_customer_information_order_switch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='user_name',
            field=models.CharField(max_length=16,verbose_name='用户名'),
        ),
    ]
