# Generated by Django 3.2.5 on 2021-07-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creat_order', '0004_alter_user_info_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='user_name',
            field=models.CharField(max_length=18, verbose_name='用户名'),
        ),
    ]
