# Generated by Django 3.2.5 on 2021-07-23 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creat_order', '0005_alter_user_info_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='rest_mode',
            fields=[
                ('rest_id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增ID')),
                ('rest', models.CharField(max_length=255, verbose_name='休息方式')),
                ('rest_value', models.CharField(max_length=255, null=True, verbose_name='对应value')),
                ('registration_time', models.DateTimeField(max_length=255, verbose_name='创建时间')),
                ('registrant', models.CharField(max_length=255, verbose_name='创建人')),
                ('revision_time', models.DateTimeField(max_length=255, null=True, verbose_name='修改时间')),
                ('reviser', models.CharField(max_length=255, null=True, verbose_name='修改人')),
            ],
        ),
        migrations.AddField(
            model_name='customer_information',
            name='rest_mode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='creat_order.rest_mode', verbose_name='休息时间'),
        ),
    ]
